### ISSUE TITLE
Broken as of 1777b54

### ISSUE THREAD

**Issue by novacrazy** [ssitu/ComfyUI_restart_sampling#6]
https://github.com/comfyanonymous/ComfyUI/commit/1777b54d0217e77a6a64b0a587b9b11a48e3bf02 appears to have broken this extension. 

```
Traceback (most recent call last):
  File "F:\sd\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\sd\ComfyUI\custom_nodes\ComfyUI_restart_sampling\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\sd\ComfyUI\custom_nodes\ComfyUI_restart_sampling\nodes.py", line 2, in <module>
    from .restart_sampling import restart_sampling, SCHEDULER_MAPPING
  File "F:\sd\ComfyUI\custom_nodes\ComfyUI_restart_sampling\restart_sampling.py", line 7, in <module>
    from comfy.samplers import CompVisVDenoiser
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (F:\sd\ComfyUI\comfy\samplers.py)
```

**Comment by xueqing0622** [comment]
Same error<
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling\nodes.py", line 2, in <module>
    from .restart_sampling import restart_sampling, SCHEDULER_MAPPING
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling\restart_sampling.py", line 7, in <module>
    from comfy.samplers import CompVisVDenoiser
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (F:\ComfyUI\ComfyUI\comfy\samplers.py)

**Comment by Piscabo** [comment]
Same here, 
_ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (F:\ComfyUI\ComfyUI\comfy\samplers.py)_

**Comment by NeedsMoar** [comment]
I temporarily fixed this by commenting out lines 7-8, 92-94,129-151, of restart_sampling.py, and 31-40 and 60 of restart_schedulers.py to remove the DDIM stuff until somebody figures it out since the whole class seems gone from comfy and I don't know what's needed.  Oddly I hadn't even used this node until today so of course it had failed to load.   DDIM will still show as available in the menus of the node, so just don't select it.  :-)  It isn't a GOOD fix, but if you have some workflow that's using this and you can do without DDIM it'll make things work for now.
